<?php $this->placeholder('title')->set('NextdoorAngels'); ?>
<fb:dashboard>
    <fb:create-button href="http://apps.facebook.com/nextdoorangels/project/add">
        Found a new social project
    </fb:create-button>
</fb:dashboard>
<b>Want to solve social problems in your neighborhood?</b>
<fb:iframe frameborder="0" marginwidth="0" marginheight="0" border="0" style="border:0;margin:0;width:750px;height:600px;" src="http://www.geowidget.de/geowidget-js/index.html?root=customers/ngo" scrolling="no" allowtransparency="true">
</fb:iframe>
