<?php $this->placeholder('title')->set('Add a social project'); ?>
<fb:header>
    NextdoorAngels - Found a new social project
</fb:header>
<fb:editor action="?do-it" labelwidth="100">
    <fb:editor-text label="Title" name="title" value=""/><fb:editor-textarea label="Description" name="description" rows="10"/><fb:editor-date label="Deadline" name="deadline"/>
    <fb:editor-custom label="Place">
        <input type="text" name="place" value=""/><!-- put google static map here -->
        <fb:iframe frameborder="0" marginwidth="0" marginheight="0" border="0" style="border:0;margin:4px 0 0 0;width:100%;height:300px;" src="http://nextdoorangels.org/project/showMap" scrolling="no" allowtransparency="true">
        </fb:iframe>
    </fb:editor-custom><!-- invite friends -->
    <fb:editor-custom label="Invitation">
        <input type="checkbox" name="send_invitation" checked="true" value="true" style="width:10%;"/>Invite all my friends
    </fb:editor-custom>
    <fb:editor-buttonset>
        <fb:editor-button value="Found project"/><fb:editor-cancel/>
    </fb:editor-buttonset>
</fb:editor>