<script type="text/javascript" src="http://www.google.com/jsapi?key=ABQIAAAAquIIHMFUJg94ExRueMgLfBRqIoZm6jji5rsO5B8qBiDUbrl1FRQdaeL1jsj3fTRyvOT7EK7euL9jmA">
</script>
<script type="text/javascript">
<!-- 
    google.load("maps", "2", {
        "other_params": "sensor=true"
    });
    
    function initialize(){
        var map = new google.maps.Map2(document.getElementById('map'));
        map.setCenter(new google.maps.LatLng(37.4419, -122.1419), 13);
    }
    
    google.setOnLoadCallback(initialize);
//--> 	
</script>
<div id="map" style="width:100%;height:300px;"></div>