<h1><fb:intl>Was ist NextdoorAngels?</fb:intl></h1>
<p><fb:intl>
	NextdoorAngels findet soziale Events in deiner Umgebung.
	<br>Nutzer von NextdoorAngels stellen soziale Events, für die Allgemeinheit nützliche Veranstaltungen, aus ihrer unmittelbaren Umgebung ein und finden dadurch Personen aus der Nachbarschaft, die sie in ihren Vorhaben unterstützen. 
</fb:intl></p>
<div>
<img src="http://nextdoorangels.org/img/mapimg.png" alt="Beispielkarte von NextDoorAngels" style="float:left;width:242px;margin-right:10px;" />
<p>
	<b><fb:intl>Beispiel:</fb:intl></b>
</p>
<p><fb:intl>
	Bernd, Papa des 3-jährigen Robins, wohnt in Wuppertal und ärgert sich immer wieder aufs Neue, dass er nie mit seinem Sohnemann zum Spielplatz um die Ecke gehen kann, weil er immer so schlimm verschmutzt ist. 
	Da er etwas ändern möchte, ruft er in NextdoorAngels dazu auf, den Spielplatz am kommenden Samstag zu reinigen. Gabi, Peter und Fred erfahren über NextdoorAngels von Bernds Idee und unterstützten ihm bei seinem Vorhaben.
</fb:intl></p>
<p><fb:intl>	
	 NextdoorAngels-User können sich auf unterschiedliche Weise beteiligen: mit einer Spende, mit Fachwissen und mit gutem Rat oder aber auch mit realem Einsatz vor Ort (Fassade neu streichen, Spielplatz säubern,...).
	 <br><br>Frei nach dem Motto: "Viele kleine Leute an vielen kleinen Orten die viele kleine Schritte gehen, können das Gesicht der Welt verändern."  
</fb:intl></p>
</div>
<div style="clear:both;"></div>
<br />
<h2><fb:intl>Unsere Mission</fb:intl></h2>
<p>
	<fb:intl>Wir haben uns nichts Kleineres vorgenommen als die Welt zu verbessern!
	<br>Aber wir leiden keineswegs an Größenwahn, sondern wir appellieren an die Nutzer der weltweit größten Internetcommunity etwas zu tun. Wenn jeder seinen Anteil leistet, dann ändert sich auch das Ganze. Seinen Anteil zu leisten bedeutet seinen tatsächlichen Wirkungskreis zu nutzen: vor der eigenen Haustür, im unmittelbaren Bekanntenkreis, im eigenen Viertel, im Alltag, immer und überall...
</fb:intl></p>
<br>
<h2><fb:intl>Die Entstehungsgeschichte</fb:intl></h2>
<p><fb:intl>
	NextdoorAngels ist 2009 an einem Startup Weekend in Nürnberg entstanden. Unter 120 Teilnehmern haben sich 5 hochmotivierte Jungunternehmer zusammengefunden und in 48 Stunden das Unternehmen NextdoorAngels gegründet.
	<br><br>Die 5 Gründer sind: Marcus Schießer, Daniel Meier, Nawid Tabibi, Bertram Gilka-Bötzow und Matthias Wulkow.
	<br><br>NextdoorAngels wird von <a href="http://geowidget.de">GEOWidget</a>, Anbieter der gleichnamigen Online GEO-Mapping Anwendung, unterstützt.
	Auch <a href="http://osbf.de">OSBF</a> (Open Source Business Foundation) danken wir für die tatkräftige Starthilfe.	
</fb:intl></p>

<br>
<h2><fb:intl>Pressemeldungen und andere Medien</fb:intl></h2>
<p>
	- <a href="http://www.maerkischeallgemeine.de/cms/beitrag/11618661/7249904/Startup-Weekend-In-Stunden-zum-Chef.html" target="_blank">NextdoorAngels Gründung in der Märkischen Allgemeinen</a><br>
	- <a href="http://www.twitter.com/nextdoorangels" target="_blank">NextdoorAngels auf Twitter #NextdoorAngels</a><br>
	- <a href="http://www.nuernberg-startups.de/2009/09/21/grundung-von-zwei-startups-auf-dem-startup-weekend-nurnberg/" target="_blank">NextdoorAngels Gründung in auf www.nuernberg-startups.de</a><br>
</p> 
<br>
<br>
<h1><a href="<?php echo $this->canvasUrl ?>"><fb:intl>Zurück zu NextdoorAngels</<fb:intl></a></h1>