<?php if($this->language == 'de') { ?>
hier sollte der deutsche text kommen, wenn er die lang erkennt
<?php } else { ?>
<h1>About NextdoorAngels</h1>
<p>
	NextDoorAngels is an online neighbourly help on Facebook. Users of NextDoorAngels create social projects within their neighborhood to find other Facebook users to supporters this project.
</p>
<div>
<img src="http://nextdoorangels.org/img/mapimg.png" alt="SampleMap of NextDoorAngels" style="float:left;width:242px;margin-right:10px;" />
<p>
	An example:
</p>
<p>
	Arnold has a three year old son and lives in Los Angeles. The playground in his neighborhood is always messy so that Arnold does not want his son to play there. He creates a new project "Keep our playground clean". Peter, Paul and Mary live in Arnold's neigborhood and feel exactly the same. Connected via Facebook and NextDoorAngels they decide to clean the playground twice a week and get more supporters with the help of Nextdoorangels.
	Users can support NextDoorAngels in many ways: A donation, knowledge or actual local help (i.e. clean playground, paint facade).
</p>
<p>	
	Our motto is: Many people on many places making many little steps will change the face of the world.
</p>
</div>
<div style="clear:both;"></div>
<br />
<h2>Our mission</h2>
<p>
	We want to change the world! Nothing less.
	It is not loss of reality we just ask for support within the world's largest internet community. If everybody does her or his share the whole world changes. And the whole world starts... next door. 
</p>
<br />
<h2>Our History</h2>
<p>
	NextDoorAngles was founded on the 1st Startup Weekend 2009 in Nürnberg. Five highly motivated entrepreneurs started NextDoorAngels within 48 hours.
	The founders are: Marcus Schießer, Daniel Meier, Nawid Tabibi, Bertram Gilka-Bötzow und Matthias Wulkow.
	NextDoorAngels is supported by <a href="http://geowidget.de">GEOWidget</a> and by <a href="http://osbf.de">OSBF</a>. Thank you very much!
</p>
<?php } ?>