<?php echo $this->headScript() ?>
<?php echo $this->headStyle() ?>
<?php echo $this->layout()->nav ?>
<fb:header><?php echo $this->placeholder('title') ?></fb:header>
<?php
if (count($this->errors) > 0) {
    echo "<fb:error>";
    foreach (($this->errors) as $key=>$value) {
        echo "<fb:message>".$key." ".$value."</fb:message>";
    }
    echo "</fb:error>";
}
?>
<?php echo $this->flashMessenger(); ?>
<?php echo $this->layout()->content ?>