<p>
	NextDoorAngels is a facebook application that is looking for local Angels. You can find social problems in your area, invite friends and organize events and projects to help solve these local issues.
</p>


The goal is to help people improve their neighborhood by working on problems together.


Some problems are just to much for one individual...

but a lot of problems could easily be solved by the community, if only they knew about the issues. Helping the community to work hand in hand together to solve local problems, thats what NextDoorAngels is all about.

By working together, you can also improve the relationship to neighbors and people from your community.


This project was started at the Startup Weekend Nuremberg #swnue. In 48 hours, the founders formed this non-profit-project from a simple question: how can we improve our every day lives and help people connect to their communities.


How you can become involved:

You can become involved in mulitple ways:

First off you can look for existing problems in your surroundings and help to fix these problems by organizing events, inviting local friends to help solve local problems.

You can also help the NextDoorAngels project by telling your friends and family about it, by becoming a fan and following us on twitter.


We will open the application source-code for the public very soon. We hope to get more developers involved into this project, as this is only the beginning of the NextDoorAngels.