<?php if($this->language == 'de') { ?>
<h1>Was ist NextdoorAngels?</h1>
<p>
	NextdoorAngels ist eine Online Nachbarschaftshilfe für Facebook (weltweit größte Internet Community mit 250 Millionen aktiven Mitgliedern).
	<br>Nutzer von NextdoorAngels stellen soziale Projekte, für die Allgemeinheit nützliche Aktionen, aus ihrer unmittelbaren Umgebung ein und finden dadurch Personen aus der Nachbarschaft, die sie in ihren Vorhaben unterstützen. 
</p>
<div>
<img src="http://nextdoorangels.org/img/mapimg.png" alt="Beispielkarte von NextDoorAngels" style="float:left;width:242px;margin-right:10px;" />
<p>
	<b>Beispiel:</b>
</p>
<p>
	Bernd, Papa des 3 jährigen Robins, wohnt in Wuppertal und ärgert sich immer wieder aufs Neue, dass er nie mit seinem Sohnemann zum Spielplatz um die Ecke gehen kann, weil er immer so schlimm verschmutzt ist. Er schildert nun die Situation in NextdoorAngels. Gabi, Peter und Fred wohnen in der Nähe und empfinden das Gleiche. Vernetzt, entscheiden sie zusammen, den Spielplatz zweimal die Woche gemeinsam aufzuräumen und nach weiterer Unterstützung zu suchen... 
</p>
<p>	
	 NextdoorAngels-User können sich auf unterschiedliche Weise beteiligen: mit einer Spende, mit Fachwissen und mit gutem Rat oder aber auch mit realem Einsatz vor Ort (Fassade neu streichen, Spielplatz säubern,...).
	 <br><br>Frei nach dem Motto: "Viele kleine Leute an vielen kleinen Orten die viele kleine Schritte gehen, können das Gesicht der Welt verändern."  
</p>
</div>
<div style="clear:both;"></div>
<br />
<h2>Unsere Mission</h2>
<p>
	Wir haben uns nichts Kleineres vorgenommen als die Welt zu verbessern!
	<br>Aber wir leiden keineswegs an Größenwahn, sondern wir appellieren an die Nutzer der weltweit größten Internetcommunity etwas zu tun. Wenn jeder seinen Anteil leistet, dann ändert sich auch das Ganze. Seinen Anteil zu leisten bedeutet seinen tatsächlichen Wirkungskreis zu nutzen: vor der eigenen Haustür, im unmittelbaren Bekanntenkreis, im eigenen Viertel, im Alltag, immer und überall...
</p>
<br>
<h2>Die Entstehungsgeschichte</h2>
<p>
	NextdoorAngels ist 2009 an einem Startup Weekend in Nürnberg entstanden. Unter 120 Teilnehmern haben sich 5 hochmotivierte Jungunternehmer zusammengefunden und in 48 Stunden das Unternehmen NextdoorAngels gegründet.
	<br><br>Die 5 Gründer sind: Marcus Schießer, Daniel Meier, Nawid Tabibi, Bertram Gilka-Bötzow und Matthias Wulkow.
	<br><br>NextdoorAngels wird von <a href="http://geowidget.de">GEOWidget</a>, Anbieter der gleichnamigen Online GEO-Mapping Anwendung, unterstützt.
	Auch <a href="http://osbf.de">OSBF</a> (Open Source Business Foundation) danken wir für die tatkräftige Starthilfe.	
</p>

<br>
<h2>Pressemeldungen und andere Medien</h2>
<p>
	- <a href="http://www.maerkischeallgemeine.de/cms/beitrag/11618661/7249904/Startup-Weekend-In-Stunden-zum-Chef.html" target="_blank">NextdoorAngels Gründung in der Märkischen Allgemeinen</a><br>
	- <a href="http://www.twitter.com/nextdoorangels" target="_blank">NextdoorAngels auf Twitter #NextdoorAngels</a><br>
	- <a href="http://www.nuernberg-startups.de/2009/09/21/grundung-von-zwei-startups-auf-dem-startup-weekend-nurnberg/" target="_blank">NextdoorAngels Gründung in auf www.nuernberg-startups.de</a><br>
</p> 
<br>
<br>
<h1><a href="<?php echo $this->canvasUrl ?>">Zurück zu NextdoorAngels</a></h1>

<?php } else { ?>
<h1>About NextdoorAngels</h1>
<p>
	NextdoorAngels is an online neighbourly help on Facebook. Users of NextDoorAngels create social projects within their neighborhood to find other Facebook users to supporters this project.
</p>
<div>
<img src="http://nextdoorangels.org/img/mapimg.png" alt="SampleMap of NextDoorAngels" style="float:left;width:242px;margin-right:10px;" />
<p>
	<b>An example:</b>
</p>
<p>
	Arnold has a three year old son and lives in Los Angeles. The playground in his neighborhood is always messy so that Arnold does not want his son to play there. He creates a new project "Keep our playground clean". Peter, Paul and Mary live in Arnold's neigborhood and feel exactly the same. Connected via Facebook and NextdoorAngels they decide to clean the playground twice a week and get more supporters with the help of Nextdoorangels.
	Users can support NextdoorAngels in many ways: A donation, knowledge or actual local help (i.e. clean playground, paint facade).
</p>
<p>	
	Our motto is: Many people on many places making many little steps will change the face of the world.
</p>
</div>
<div style="clear:both;"></div>
<br />
<h2>Our Mission</h2>
<p>
	We want to change the world! Nothing less.
	It is not loss of reality we just ask for support within the world's largest internet community. If everybody does her or his share the whole world changes. And the whole world starts... next door. 
</p>
<br />
<h2>Our History</h2>
<p>
	NextdoorAngles was founded on the 1st Startup Weekend 2009 in Nürnberg. Five highly motivated entrepreneurs started NextdoorAngels within 48 hours.
	The founders are: Marcus Schießer, Daniel Meier, Nawid Tabibi, Bertram Gilka-Bötzow and Matthias Wulkow.<br><br>
	NextDoorAngels is supported by <a href="http://geowidget.de">GEOWidget</a> and by <a href="http://osbf.de">OSBF</a>. Thank you very much!
</p>
<br>
<h2>Press</h2>
<p>
	- <a href="http://www.maerkischeallgemeine.de/cms/beitrag/11618661/7249904/Startup-Weekend-In-Stunden-zum-Chef.html" target="_blank">NextdoorAngels in "Märkische Allgemeine"</a><br>
	- <a href="http://www.twitter.com/nextdoorangels" target="_blank">NextdoorAngels on Twitter #NextdoorAngels</a><br>
	- <a href="http://www.nuernberg-startups.de/2009/09/21/grundung-von-zwei-startups-auf-dem-startup-weekend-nurnberg/" target="_blank">NextdoorAngels on www.nuernberg-startups.de</a><br>
</p> 
<br>
<br>
<h1><a href="<?php echo $this->canvasUrl ?>">Back to NextdoorAngels</a></h1>



<?php } 
